"""Small QGIS-expression helpers used by the guided FILTER editor.

The helpers are deliberately QGIS-free.  They keep the visual authoring layer
focused on choosing values while preserving the canonical expression parameter
already consumed by the explicit graph executor.
"""

from decimal import Decimal, InvalidOperation
import re
from typing import Optional


FILTER_OPERATORS = (
    ("equals", "equals"),
    ("not_equal", "not equal"),
    ("greater_than", "greater than"),
    ("greater_equal", "greater than or equal to"),
    ("less_than", "less than"),
    ("less_equal", "less than or equal to"),
    ("contains", "contains"),
    ("starts_with", "starts with"),
    ("ends_with", "ends with"),
    ("is_null", "is null"),
    ("is_not_null", "is not null"),
)

_OPERATOR_ALIASES = {
    "=": "equals",
    "==": "equals",
    "<>": "not_equal",
    "!=": "not_equal",
    ">": "greater_than",
    ">=": "greater_equal",
    "<": "less_than",
    "<=": "less_equal",
    "like": "contains",
}


def quote_field_name(field_name: str) -> str:
    """Quote a QGIS field identifier, including embedded double quotes."""

    field_name = str(field_name or "").strip()
    if not field_name:
        raise ValueError("Choose a field before configuring FILTER.")
    return '"' + field_name.replace('"', '""') + '"'


def quote_string_value(value: str) -> str:
    """Quote a QGIS string literal without allowing apostrophes to terminate it."""

    return "'" + str(value).replace("'", "''") + "'"


def normalize_operator(operator: str) -> str:
    key = str(operator or "").strip().lower()
    return _OPERATOR_ALIASES.get(key, key)


def normalize_field_type(field_type: Optional[str]) -> str:
    value = str(field_type or "string").lower()
    if any(token in value for token in ("bool", "boolean")):
        return "boolean"
    if any(
        token in value
        for token in (
            "int",
            "long",
            "short",
            "double",
            "float",
            "real",
            "decimal",
            "numeric",
            "number",
        )
    ):
        return "number"
    return "string"


def _literal(value: str, field_type: Optional[str]) -> str:
    kind = normalize_field_type(field_type)
    if kind == "boolean":
        normalized = str(value or "").strip().lower()
        if normalized in {"true", "1", "yes"}:
            return "true"
        if normalized in {"false", "0", "no"}:
            return "false"
        raise ValueError("Enter true or false for a boolean field.")
    if kind == "number":
        normalized = str(value or "").strip()
        if not normalized:
            raise ValueError("Enter a numeric value for this field.")
        try:
            number = Decimal(normalized)
        except InvalidOperation as exc:
            raise ValueError("Enter a valid numeric value for this field.") from exc
        if not number.is_finite():
            raise ValueError("Enter a finite numeric value for this field.")
        return format(number, "f")
    return quote_string_value(value)


def build_filter_expression(
    field_name: str,
    operator: str,
    value: str = "",
    field_type: Optional[str] = "string",
) -> str:
    """Build one canonical, executor-compatible QGIS FILTER expression."""

    field = quote_field_name(field_name)
    operation = normalize_operator(operator)
    if operation == "is_null":
        return f"{field} IS NULL"
    if operation == "is_not_null":
        return f"{field} IS NOT NULL"

    literal = _literal(value, field_type)
    operators = {
        "equals": "=",
        "not_equal": "<>",
        "greater_than": ">",
        "greater_equal": ">=",
        "less_than": "<",
        "less_equal": "<=",
    }
    if operation in operators:
        return f"{field} {operators[operation]} {literal}"
    if operation in {"contains", "starts_with", "ends_with"}:
        if normalize_field_type(field_type) != "string":
            raise ValueError("Contains, starts with and ends with require a text field.")
        pattern = {
            "contains": f"%{value}%",
            "starts_with": f"{value}%",
            "ends_with": f"%{value}",
        }[operation]
        return f"{field} LIKE {quote_string_value(pattern)}"
    raise ValueError(f"Unsupported FILTER condition: {operator!r}.")


_SIMPLE_COMPARISON = re.compile(r'^\s*"((?:""|[^"])*)"\s*(>=|<=|<>|=|>|<)\s*(.*?)\s*$')
_SIMPLE_LIKE = re.compile(r'^\s*"((?:""|[^"])*)"\s+LIKE\s+\'(.*)\'\s*$', re.IGNORECASE)


def parse_simple_filter_expression(expression: str):
    """Decompose expressions generated by :func:`build_filter_expression`.

    Unknown expressions return ``None`` so the UI can keep them intact in the
    advanced QGIS expression editor instead of guessing at their meaning.
    """

    text = str(expression or "").strip()
    null_match = re.fullmatch(
        r'"((?:""|[^"])*)"\s+IS\s+(NOT\s+)?NULL', text, re.IGNORECASE
    )
    if null_match:
        field = null_match.group(1).replace('""', '"')
        return field, "is_not_null" if null_match.group(2) else "is_null", "", "string"

    like_match = _SIMPLE_LIKE.fullmatch(text)
    if like_match:
        field = like_match.group(1).replace('""', '"')
        pattern = like_match.group(2).replace("''", "'")
        if pattern.startswith("%") and pattern.endswith("%"):
            return field, "contains", pattern[1:-1], "string"
        if pattern.endswith("%"):
            return field, "starts_with", pattern[:-1], "string"
        if pattern.startswith("%"):
            return field, "ends_with", pattern[1:], "string"
        return None

    match = _SIMPLE_COMPARISON.fullmatch(text)
    if not match:
        return None
    field = match.group(1).replace('""', '"')
    operator = {
        "=": "equals",
        "<>": "not_equal",
        ">": "greater_than",
        ">=": "greater_equal",
        "<": "less_than",
        "<=": "less_equal",
    }[match.group(2)]
    literal = match.group(3).strip()
    if len(literal) >= 2 and literal[0] == "'" and literal[-1] == "'":
        return field, operator, literal[1:-1].replace("''", "'"), "string"
    if literal.lower() in {"true", "false"}:
        return field, operator, literal.lower(), "boolean"
    try:
        Decimal(literal)
    except InvalidOperation:
        return None
    return field, operator, literal, "number"


# Friendly aliases for callers that prefer a verb-oriented name.
generate_filter_expression = build_filter_expression
