"""Pure adapter from generic PropagationPlan to the proven v0.1 executor targets."""

from dataclasses import dataclass
from typing import FrozenSet, Iterable, Optional

from ..models.dependency_graph import PropagationPlan, plan_propagation
from ..models.workflow import LEGACY_GRAPH_ORIGIN


class SelectiveExecutionError(ValueError):
    """Raised when a generic selection cannot be executed honestly by v0.1."""


@dataclass(frozen=True)
class LegacyExecutionPlan:
    propagation: PropagationPlan
    refresh_layer_c: bool
    refresh_gpkg: bool
    export_ids: FrozenSet[str]
    delivery_ids: FrozenSet[str]
    # Downstream nodes actually regenerated by this run. Changed source nodes are
    # already recorded separately in ``propagation.changed_node_ids``.
    refreshed_node_ids: FrozenSet[str]


def plan_legacy_execution(
    workflow,
    changed_source_lineage_ids: Iterable[str],
    selected_edge_ids: Optional[Iterable[str]] = None,
) -> LegacyExecutionPlan:
    """Map one selective graph run onto existing Layer C/GPKG/XLSX services.

    The current v0.1 Layer C builder always reads the current state of every
    registered source. Therefore, when multiple source nodes changed, it cannot
    honestly rebuild a merge target while accepting one changed parent and
    omitting another. That ambiguous partial-parent case is blocked rather than
    silently leaking an unselected source change into Layer C.
    """

    if workflow.effective_dependency_graph_origin() != LEGACY_GRAPH_ORIGIN:
        raise SelectiveExecutionError(
            "G5 selective execution currently supports the proven legacy v0.1 adapter only."
        )

    graph = workflow.effective_dependency_graph()
    source_nodes = {
        str(node.metadata.get("source_lineage_id") or ""): node.node_id
        for node in graph.nodes
        if node.metadata.get("source_lineage_id")
    }
    requested_lineage = {
        str(item) for item in changed_source_lineage_ids if str(item)
    }
    unknown = requested_lineage - set(source_nodes)
    if unknown:
        raise SelectiveExecutionError(
            "Changed source lineage is not present in the workflow graph: "
            + ", ".join(sorted(unknown))
        )
    if not requested_lineage:
        raise SelectiveExecutionError("At least one changed source lineage is required.")

    changed_nodes = {source_nodes[item] for item in requested_lineage}
    propagation = plan_propagation(graph, changed_nodes, selected_edge_ids)

    derived_node_id = "derived:primary"
    derived_affected = derived_node_id in propagation.affected_node_ids
    derived_stale = derived_node_id in propagation.stale_by_choice_node_ids
    if derived_affected and derived_stale:
        raise SelectiveExecutionError(
            "The selected run would partially refresh Layer C from only some changed parents. "
            "The v0.1 merge executor cannot isolate already-changed source versions safely; "
            "select all changed parent edges into Layer C or skip Layer C for this run."
        )

    refresh_layer_c = derived_affected
    refresh_gpkg = (
        refresh_layer_c
        and "delivery:gpkg" in propagation.affected_node_ids
        and "delivery:gpkg" not in propagation.stale_by_choice_node_ids
    )

    export_ids = set()
    delivery_ids = set()
    refreshed_nodes = set()
    if refresh_layer_c:
        refreshed_nodes.add(derived_node_id)
        if refresh_gpkg:
            refreshed_nodes.add("delivery:gpkg")
        for node in graph.nodes:
            export_id = str(node.metadata.get("export_id") or "")
            if export_id and (
                node.node_id in propagation.affected_node_ids
                and node.node_id not in propagation.stale_by_choice_node_ids
            ):
                export_ids.add(export_id)
                refreshed_nodes.add(node.node_id)
            delivery_id = str(node.metadata.get("delivery_id") or "")
            if (
                delivery_id
                and node.node_id in propagation.affected_node_ids
                and node.node_id not in propagation.stale_by_choice_node_ids
            ):
                delivery_ids.add(delivery_id)
                refreshed_nodes.add(node.node_id)

    return LegacyExecutionPlan(
        propagation=propagation,
        refresh_layer_c=refresh_layer_c,
        refresh_gpkg=refresh_gpkg,
        export_ids=frozenset(export_ids),
        delivery_ids=frozenset(delivery_ids),
        refreshed_node_ids=frozenset(refreshed_nodes),
    )
